export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav
          style={{
            padding: "1rem",
            background: "#e0f2fe",
            display: "flex",
            justifyContent: "flex-end",
          }}
        ></nav>
        {children}
      </body>
    </html>
  );
}
